import type { NodeDefinition } from './types';

export const appNodes: NodeDefinition[] = [
  // === IMAGE SERVICES ===
  {
    type: 'action_pexels',
    category: 'apps',
    name: 'Pexels Image',
    icon: '📷',
    color: '#05a081',
    description: 'Search for images on Pexels',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Image URL' }],
    defaultData: { apiKey: '', query: '', size: 'large', orientation: '' },
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Your Pexels API key', required: true },
      { key: 'query', label: 'Search Query', type: 'text', placeholder: '{{topic}} or keywords', required: true },
      { key: 'size', label: 'Image Size', type: 'select', options: [
        { value: 'original', label: 'Original' },
        { value: 'large2x', label: 'Large 2x' },
        { value: 'large', label: 'Large' },
        { value: 'medium', label: 'Medium' },
        { value: 'small', label: 'Small' },
      ]},
      { key: 'orientation', label: 'Orientation', type: 'select', options: [
        { value: '', label: 'Any' },
        { value: 'landscape', label: 'Landscape' },
        { value: 'portrait', label: 'Portrait' },
        { value: 'square', label: 'Square' },
      ]},
    ],
  },
  {
    type: 'action_unsplash',
    category: 'apps',
    name: 'Unsplash Image',
    icon: '🖼️',
    color: '#000000',
    description: 'Search for images on Unsplash',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Image URL' }],
    defaultData: { apiKey: '', query: '', size: 'regular', orientation: '' },
    fields: [
      { key: 'apiKey', label: 'Access Key', type: 'password', placeholder: 'Your Unsplash Access Key', required: true },
      { key: 'query', label: 'Search Query', type: 'text', placeholder: '{{topic}} or keywords', required: true },
      { key: 'size', label: 'Image Size', type: 'select', options: [
        { value: 'raw', label: 'Raw (Original)' },
        { value: 'full', label: 'Full' },
        { value: 'regular', label: 'Regular (1080px)' },
        { value: 'small', label: 'Small (400px)' },
        { value: 'thumb', label: 'Thumbnail (200px)' },
      ]},
      { key: 'orientation', label: 'Orientation', type: 'select', options: [
        { value: '', label: 'Any' },
        { value: 'landscape', label: 'Landscape' },
        { value: 'portrait', label: 'Portrait' },
        { value: 'squarish', label: 'Square' },
      ]},
    ],
  },

  // === COMMUNICATION ===
  {
    type: 'action_telegram',
    category: 'apps',
    name: 'Telegram Message',
    icon: '✈️',
    color: '#0088cc',
    description: 'Send message via Telegram Bot',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Result' }],
    defaultData: { botToken: '', chatId: '', message: '', parseMode: 'HTML' },
    fields: [
      { key: 'botToken', label: 'Bot Token', type: 'password', placeholder: '123456:ABC-DEF...', required: true },
      { key: 'chatId', label: 'Chat ID', type: 'text', placeholder: '@channel or user ID', required: true },
      { key: 'message', label: 'Message', type: 'textarea', placeholder: '{{output}} or text', required: true },
      { key: 'parseMode', label: 'Parse Mode', type: 'select', options: [
        { value: 'HTML', label: 'HTML' },
        { value: 'Markdown', label: 'Markdown' },
        { value: '', label: 'Plain Text' },
      ]},
    ],
  },
  {
    type: 'action_discord',
    category: 'apps',
    name: 'Discord Webhook',
    icon: '💬',
    color: '#5865F2',
    description: 'Send message to Discord channel',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Result' }],
    defaultData: { webhookUrl: '', content: '', username: '', avatarUrl: '' },
    fields: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'password', placeholder: 'https://discord.com/api/webhooks/...', required: true },
      { key: 'content', label: 'Message', type: 'textarea', placeholder: '{{output}} or text', required: true },
      { key: 'username', label: 'Bot Name (optional)', type: 'text', placeholder: 'Custom bot name' },
      { key: 'avatarUrl', label: 'Avatar URL (optional)', type: 'text', placeholder: 'https://...' },
    ],
  },
  {
    type: 'action_slack',
    category: 'apps',
    name: 'Slack Webhook',
    icon: '📢',
    color: '#4A154B',
    description: 'Send message to Slack channel',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Result' }],
    defaultData: { webhookUrl: '', text: '', username: '', iconEmoji: '' },
    fields: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'password', placeholder: 'https://hooks.slack.com/services/...', required: true },
      { key: 'text', label: 'Message', type: 'textarea', placeholder: '{{output}} or text', required: true },
      { key: 'username', label: 'Bot Name (optional)', type: 'text', placeholder: 'Custom bot name' },
      { key: 'iconEmoji', label: 'Icon Emoji (optional)', type: 'text', placeholder: ':robot_face:' },
    ],
  },
  {
    type: 'action_email',
    category: 'apps',
    name: 'Send Email',
    icon: '📧',
    color: '#EA4335',
    description: 'Send email via SMTP',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Result' }],
    defaultData: { smtpHost: '', smtpPort: '587', username: '', password: '', from: '', to: '', subject: '', body: '', isHtml: true },
    fields: [
      { key: 'smtpHost', label: 'SMTP Host', type: 'text', placeholder: 'smtp.gmail.com', required: true },
      { key: 'smtpPort', label: 'SMTP Port', type: 'text', placeholder: '587', defaultValue: '587' },
      { key: 'username', label: 'Username', type: 'text', placeholder: 'your@email.com', required: true },
      { key: 'password', label: 'Password', type: 'password', placeholder: 'App password', required: true },
      { key: 'from', label: 'From', type: 'text', placeholder: 'sender@email.com', required: true },
      { key: 'to', label: 'To', type: 'text', placeholder: 'recipient@email.com', required: true },
      { key: 'subject', label: 'Subject', type: 'text', placeholder: '{{topic}}', required: true },
      { key: 'body', label: 'Body', type: 'textarea', placeholder: '{{output}}', required: true },
      { key: 'isHtml', label: 'HTML Email', type: 'boolean', defaultValue: true },
    ],
  },

  // === TRANSLATION ===
  {
    type: 'action_translate',
    category: 'apps',
    name: 'Google Translate',
    icon: '🌐',
    color: '#4285F4',
    description: 'Translate text using Google Translate',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Translated' }],
    defaultData: { text: '', from: 'auto', to: 'en' },
    fields: [
      { key: 'text', label: 'Text', type: 'textarea', placeholder: '{{output}} or text to translate', required: true },
      { key: 'from', label: 'From Language', type: 'select', options: [
        { value: 'auto', label: 'Auto Detect' },
        { value: 'en', label: 'English' },
        { value: 'es', label: 'Spanish' },
        { value: 'fr', label: 'French' },
        { value: 'de', label: 'German' },
        { value: 'it', label: 'Italian' },
        { value: 'pt', label: 'Portuguese' },
        { value: 'ru', label: 'Russian' },
        { value: 'ja', label: 'Japanese' },
        { value: 'ko', label: 'Korean' },
        { value: 'zh', label: 'Chinese' },
        { value: 'ar', label: 'Arabic' },
        { value: 'hi', label: 'Hindi' },
      ]},
      { key: 'to', label: 'To Language', type: 'select', options: [
        { value: 'en', label: 'English' },
        { value: 'es', label: 'Spanish' },
        { value: 'fr', label: 'French' },
        { value: 'de', label: 'German' },
        { value: 'it', label: 'Italian' },
        { value: 'pt', label: 'Portuguese' },
        { value: 'ru', label: 'Russian' },
        { value: 'ja', label: 'Japanese' },
        { value: 'ko', label: 'Korean' },
        { value: 'zh', label: 'Chinese' },
        { value: 'ar', label: 'Arabic' },
        { value: 'hi', label: 'Hindi' },
      ]},
    ],
  },

  // === DATA & NEWS ===
  {
    type: 'action_weather',
    category: 'apps',
    name: 'Weather',
    icon: '🌤️',
    color: '#00BFFF',
    description: 'Get current weather data',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Weather' }],
    defaultData: { apiKey: '', city: '', units: 'metric' },
    fields: [
      { key: 'apiKey', label: 'OpenWeather API Key', type: 'password', placeholder: 'Your API key', required: true },
      { key: 'city', label: 'City', type: 'text', placeholder: 'London or {{city}}', required: true },
      { key: 'units', label: 'Units', type: 'select', options: [
        { value: 'metric', label: 'Celsius' },
        { value: 'imperial', label: 'Fahrenheit' },
      ]},
    ],
  },
  {
    type: 'action_rss',
    category: 'apps',
    name: 'RSS Feed',
    icon: '📰',
    color: '#FFA500',
    description: 'Fetch RSS/Atom feed',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Items' }],
    defaultData: { url: '', limit: 10 },
    fields: [
      { key: 'url', label: 'Feed URL', type: 'text', placeholder: 'https://example.com/feed.xml', required: true },
      { key: 'limit', label: 'Max Items', type: 'number', placeholder: '10', defaultValue: 10 },
    ],
  },

  // === URL SHORTENER ===
  {
    type: 'action_shorten_url',
    category: 'apps',
    name: 'Shorten URL',
    icon: '🔗',
    color: '#2BD17E',
    description: 'Shorten URL using TinyURL',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Short URL' }],
    defaultData: { url: '' },
    fields: [
      { key: 'url', label: 'Long URL', type: 'text', placeholder: 'https://example.com/very/long/url', required: true },
    ],
  },

  // === QR CODE ===
  {
    type: 'action_qrcode',
    category: 'apps',
    name: 'QR Code Pro',
    icon: '📱',
    color: '#000000',
    description: 'Generate customizable QR codes',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'QR Result' }],
    defaultData: { data: '', size: '300', format: 'png', color: '000000', bgcolor: 'ffffff', margin: '1', ecc: 'M' },
    fields: [
      { key: 'data', label: 'Data/URL', type: 'textarea', placeholder: 'https://example.com, text, vCard, WiFi config...', required: true },
      { key: 'size', label: 'Size (px)', type: 'select', options: [
        { value: '150', label: '150x150 (Small)' },
        { value: '200', label: '200x200' },
        { value: '300', label: '300x300 (Default)' },
        { value: '400', label: '400x400' },
        { value: '500', label: '500x500' },
        { value: '600', label: '600x600' },
        { value: '800', label: '800x800 (Large)' },
        { value: '1000', label: '1000x1000 (HD)' },
      ]},
      { key: 'format', label: 'Format', type: 'select', options: [
        { value: 'png', label: 'PNG (Recommended)' },
        { value: 'svg', label: 'SVG (Vector)' },
        { value: 'eps', label: 'EPS (Print)' },
        { value: 'gif', label: 'GIF' },
        { value: 'jpg', label: 'JPG' },
      ]},
      { key: 'ecc', label: 'Error Correction', type: 'select', options: [
        { value: 'L', label: 'Low (7% recovery)' },
        { value: 'M', label: 'Medium (15% recovery)' },
        { value: 'Q', label: 'Quartile (25% recovery)' },
        { value: 'H', label: 'High (30% recovery)' },
      ]},
      { key: 'color', label: 'QR Color (hex)', type: 'text', placeholder: '000000 (black)', defaultValue: '000000' },
      { key: 'bgcolor', label: 'Background (hex)', type: 'text', placeholder: 'ffffff (white)', defaultValue: 'ffffff' },
      { key: 'margin', label: 'Margin (modules)', type: 'select', options: [
        { value: '0', label: 'None' },
        { value: '1', label: '1 (Minimal)' },
        { value: '2', label: '2 (Default)' },
        { value: '4', label: '4 (Large)' },
      ]},
    ],
  },

  // === GITHUB ===
  {
    type: 'action_github',
    category: 'apps',
    name: 'GitHub API',
    icon: '🐙',
    color: '#333333',
    description: 'Interact with GitHub API',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Response' }],
    defaultData: { token: '', action: 'repos', owner: '', repo: '' },
    fields: [
      { key: 'token', label: 'Personal Access Token', type: 'password', placeholder: 'ghp_...', required: true },
      { key: 'action', label: 'Action', type: 'select', options: [
        { value: 'repos', label: 'List Repositories' },
        { value: 'repo', label: 'Get Repository Info' },
        { value: 'issues', label: 'List Issues' },
        { value: 'commits', label: 'List Commits' },
        { value: 'releases', label: 'List Releases' },
      ]},
      { key: 'owner', label: 'Owner/Org', type: 'text', placeholder: 'username or org' },
      { key: 'repo', label: 'Repository', type: 'text', placeholder: 'repo-name' },
    ],
  },

  // === NOTION ===
  {
    type: 'action_notion',
    category: 'apps',
    name: 'Notion',
    icon: '📓',
    color: '#000000',
    description: 'Add page to Notion database',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Page' }],
    defaultData: { apiKey: '', databaseId: '', title: '', content: '' },
    fields: [
      { key: 'apiKey', label: 'Integration Token', type: 'password', placeholder: 'secret_...', required: true },
      { key: 'databaseId', label: 'Database ID', type: 'text', placeholder: 'Database ID from URL', required: true },
      { key: 'title', label: 'Page Title', type: 'text', placeholder: '{{topic}}', required: true },
      { key: 'content', label: 'Content', type: 'textarea', placeholder: '{{output}}' },
    ],
  },

  // === PRO: AI SERVICES ===
  // OpenAI and Claude nodes removed - use the generic AI node instead

  // === PRO: GOOGLE SERVICES ===
  {
    type: 'action_youtube',
    category: 'apps',
    name: 'YouTube Search',
    icon: '▶️',
    color: '#FF0000',
    description: 'Search YouTube videos',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Videos' }],
    defaultData: { apiKey: '', query: '', maxResults: 5, type: 'video' },
    fields: [
      { key: 'apiKey', label: 'YouTube API Key', type: 'password', placeholder: 'Your API key', required: true },
      { key: 'query', label: 'Search Query', type: 'text', placeholder: '{{topic}}', required: true },
      { key: 'maxResults', label: 'Max Results', type: 'number', placeholder: '5', defaultValue: 5 },
      { key: 'type', label: 'Type', type: 'select', options: [
        { value: 'video', label: 'Videos' },
        { value: 'channel', label: 'Channels' },
        { value: 'playlist', label: 'Playlists' },
      ]},
    ],
  },
  {
    type: 'action_google_sheets',
    category: 'apps',
    name: 'Google Sheets',
    icon: '📊',
    color: '#0F9D58',
    description: 'Read/Write Google Sheets',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Data' }],
    defaultData: { apiKey: '', spreadsheetId: '', range: 'Sheet1!A1:Z100', action: 'read', data: '' },
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Your API key', required: true },
      { key: 'spreadsheetId', label: 'Spreadsheet ID', type: 'text', placeholder: 'From URL: /d/{ID}/edit', required: true },
      { key: 'action', label: 'Action', type: 'select', options: [
        { value: 'read', label: 'Read Data' },
        { value: 'append', label: 'Append Row' },
      ]},
      { key: 'range', label: 'Range', type: 'text', placeholder: 'Sheet1!A1:Z100', defaultValue: 'Sheet1!A1:Z100' },
      { key: 'data', label: 'Data (for append)', type: 'textarea', placeholder: '["col1", "col2"] or {{output}}' },
    ],
  },

  // === PRO: SOCIAL MEDIA ===
  {
    type: 'action_twitter',
    category: 'apps',
    name: 'Twitter/X Post',
    icon: '🐦',
    color: '#1DA1F2',
    description: 'Post tweet to Twitter/X',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Tweet' }],
    defaultData: { apiKey: '', apiSecret: '', accessToken: '', accessSecret: '', text: '' },
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Consumer Key', required: true },
      { key: 'apiSecret', label: 'API Secret', type: 'password', placeholder: 'Consumer Secret', required: true },
      { key: 'accessToken', label: 'Access Token', type: 'password', placeholder: 'Access Token', required: true },
      { key: 'accessSecret', label: 'Access Secret', type: 'password', placeholder: 'Access Token Secret', required: true },
      { key: 'text', label: 'Tweet Text', type: 'textarea', placeholder: '{{output}} (max 280 chars)', required: true },
    ],
  },
  {
    type: 'action_linkedin',
    category: 'apps',
    name: 'LinkedIn Post',
    icon: '💼',
    color: '#0077B5',
    description: 'Post to LinkedIn',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Post' }],
    defaultData: { accessToken: '', text: '' },
    fields: [
      { key: 'accessToken', label: 'Access Token', type: 'password', placeholder: 'OAuth Access Token', required: true },
      { key: 'text', label: 'Post Text', type: 'textarea', placeholder: '{{output}}', required: true },
    ],
  },

  // === PRO: E-COMMERCE ===
  // Stripe node removed

  // === PRO: DATABASE ===
  {
    type: 'action_airtable',
    category: 'apps',
    name: 'Airtable',
    icon: '📋',
    color: '#18BFFF',
    description: 'Read/Write Airtable records',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Records' }],
    defaultData: { apiKey: '', baseId: '', tableName: '', action: 'list', recordId: '', fields: '' },
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'pat...', required: true },
      { key: 'baseId', label: 'Base ID', type: 'text', placeholder: 'app...', required: true },
      { key: 'tableName', label: 'Table Name', type: 'text', placeholder: 'Table 1', required: true },
      { key: 'action', label: 'Action', type: 'select', options: [
        { value: 'list', label: 'List Records' },
        { value: 'get', label: 'Get Record' },
        { value: 'create', label: 'Create Record' },
        { value: 'update', label: 'Update Record' },
        { value: 'delete', label: 'Delete Record' },
      ]},
      { key: 'recordId', label: 'Record ID (for get/update/delete)', type: 'text', placeholder: 'rec...' },
      { key: 'fields', label: 'Fields JSON (for create/update)', type: 'textarea', placeholder: '{"Name": "{{name}}"}' },
    ],
  },
  {
    type: 'action_supabase',
    category: 'apps',
    name: 'Supabase',
    icon: '⚡',
    color: '#3ECF8E',
    description: 'Supabase database operations',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Data' }],
    defaultData: { url: '', apiKey: '', table: '', action: 'select', data: '', filters: '' },
    fields: [
      { key: 'url', label: 'Project URL', type: 'text', placeholder: 'https://xxx.supabase.co', required: true },
      { key: 'apiKey', label: 'API Key (anon)', type: 'password', placeholder: 'eyJ...', required: true },
      { key: 'table', label: 'Table Name', type: 'text', placeholder: 'users', required: true },
      { key: 'action', label: 'Action', type: 'select', options: [
        { value: 'select', label: 'Select (Read)' },
        { value: 'insert', label: 'Insert (Create)' },
        { value: 'update', label: 'Update' },
        { value: 'delete', label: 'Delete' },
      ]},
      { key: 'data', label: 'Data JSON (for insert/update)', type: 'textarea', placeholder: '{"name": "{{name}}"}' },
      { key: 'filters', label: 'Filters (for select/update/delete)', type: 'text', placeholder: 'id=eq.1' },
    ],
  },

  // === PRO: AUTOMATION ===
  {
    type: 'action_zapier',
    category: 'apps',
    name: 'Zapier Webhook',
    icon: '⚡',
    color: '#FF4A00',
    description: 'Trigger Zapier webhook',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Result' }],
    defaultData: { webhookUrl: '', data: '' },
    fields: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'password', placeholder: 'https://hooks.zapier.com/...', required: true },
      { key: 'data', label: 'Data (JSON)', type: 'textarea', placeholder: '{{output}} or {"key": "value"}' },
    ],
  },
  {
    type: 'action_make',
    category: 'apps',
    name: 'Make Webhook',
    icon: '🔄',
    color: '#6D00CC',
    description: 'Trigger Make (Integromat) webhook',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Result' }],
    defaultData: { webhookUrl: '', data: '' },
    fields: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'password', placeholder: 'https://hook.make.com/...', required: true },
      { key: 'data', label: 'Data (JSON)', type: 'textarea', placeholder: '{{output}} or {"key": "value"}' },
    ],
  },

  // === PRO: CLOUD STORAGE ===
  {
    type: 'action_dropbox',
    category: 'apps',
    name: 'Dropbox',
    icon: '📦',
    color: '#0061FF',
    description: 'Upload/Download from Dropbox',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Result' }],
    defaultData: { accessToken: '', action: 'list', path: '', content: '' },
    fields: [
      { key: 'accessToken', label: 'Access Token', type: 'password', placeholder: 'sl.B...', required: true },
      { key: 'action', label: 'Action', type: 'select', options: [
        { value: 'list', label: 'List Files' },
        { value: 'download', label: 'Download File' },
        { value: 'upload', label: 'Upload Text File' },
      ]},
      { key: 'path', label: 'Path', type: 'text', placeholder: '/folder/file.txt', required: true },
      { key: 'content', label: 'Content (for upload)', type: 'textarea', placeholder: '{{output}}' },
    ],
  },

  // === PRO: ANALYTICS ===
  {
    type: 'action_mixpanel',
    category: 'apps',
    name: 'Mixpanel Track',
    icon: '📈',
    color: '#7856FF',
    description: 'Track event in Mixpanel',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Result' }],
    defaultData: { token: '', event: '', distinctId: '', properties: '' },
    fields: [
      { key: 'token', label: 'Project Token', type: 'password', placeholder: 'Your project token', required: true },
      { key: 'event', label: 'Event Name', type: 'text', placeholder: 'Button Clicked', required: true },
      { key: 'distinctId', label: 'User ID', type: 'text', placeholder: '{{userId}}', required: true },
      { key: 'properties', label: 'Properties (JSON)', type: 'textarea', placeholder: '{"plan": "pro"}' },
    ],
  },

  // === FILE HOSTING ===
  {
    type: 'action_litterbox',
    category: 'apps',
    name: 'Litterbox Upload',
    icon: '🐱',
    color: '#f59e0b',
    description: 'Upload temporary file to Litterbox (1h-72h)',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'URL' }],
    defaultData: { filePath: '', expiry: '24h' },
    fields: [
      { key: 'filePath', label: 'File Path', type: 'file', placeholder: '/path/to/file.png', required: true },
      { key: 'expiry', label: 'Expiry Time', type: 'select', options: [
        { value: '1h', label: '1 Hour' },
        { value: '12h', label: '12 Hours' },
        { value: '24h', label: '24 Hours' },
        { value: '72h', label: '72 Hours (3 Days)' },
      ]},
    ],
  },
  {
    type: 'action_catbox',
    category: 'apps',
    name: 'Catbox',
    icon: '📦',
    color: '#8b5cf6',
    description: 'Upload file to Catbox (permanent)',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Result' }],
    defaultData: { action: 'upload', filePath: '', url: '', userhash: '', files: '', albumShort: '', title: '', desc: '' },
    fields: [
      { key: 'action', label: 'Action', type: 'select', options: [
        { value: 'upload', label: 'Upload File' },
        { value: 'urlupload', label: 'Upload from URL' },
        { value: 'delete', label: 'Delete Files' },
        { value: 'createalbum', label: 'Create Album' },
        { value: 'editalbum', label: 'Edit Album' },
        { value: 'addtoalbum', label: 'Add to Album' },
        { value: 'removefromalbum', label: 'Remove from Album' },
        { value: 'deletealbum', label: 'Delete Album' },
      ]},
      { key: 'userhash', label: 'User Hash (optional)', type: 'password', placeholder: 'For account uploads' },
      { key: 'filePath', label: 'File Path (for upload)', type: 'file', placeholder: '/path/to/file.png' },
      { key: 'url', label: 'URL (for urlupload)', type: 'text', placeholder: 'https://example.com/image.jpg' },
      { key: 'files', label: 'Files (space-separated)', type: 'text', placeholder: 'abc123.png def456.gif' },
      { key: 'albumShort', label: 'Album Short (6 chars)', type: 'text', placeholder: 'pd412w' },
      { key: 'title', label: 'Album Title', type: 'text', placeholder: 'My Album' },
      { key: 'desc', label: 'Album Description', type: 'text', placeholder: 'Album description' },
    ],
  },

  // === PRO: CRM ===
  {
    type: 'action_hubspot',
    category: 'apps',
    name: 'HubSpot',
    icon: '🧡',
    color: '#FF7A59',
    description: 'HubSpot CRM operations',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Result' }],
    defaultData: { apiKey: '', action: 'contacts', contactId: '', properties: '' },
    fields: [
      { key: 'apiKey', label: 'Private App Token', type: 'password', placeholder: 'pat-...', required: true },
      { key: 'action', label: 'Action', type: 'select', options: [
        { value: 'contacts', label: 'List Contacts' },
        { value: 'contact', label: 'Get Contact' },
        { value: 'create_contact', label: 'Create Contact' },
        { value: 'deals', label: 'List Deals' },
        { value: 'companies', label: 'List Companies' },
      ]},
      { key: 'contactId', label: 'Contact ID (optional)', type: 'text', placeholder: '123' },
      { key: 'properties', label: 'Properties (for create)', type: 'textarea', placeholder: '{"email": "{{email}}"}' },
    ],
  },

  // === AI IMAGE GENERATION ===
  {
    type: 'action_openai_image',
    category: 'apps',
    name: 'OpenAI Image (DALL-E)',
    icon: '🎨',
    color: '#10a37f',
    description: 'Generate images with DALL-E',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Image URL' }],
    defaultData: { apiKey: '', prompt: '', size: '1024x1024', model: 'dall-e-3', quality: 'standard', style: 'vivid' },
    fields: [
      { key: 'apiKey', label: 'OpenAI API Key', type: 'password', placeholder: 'sk-...', required: true },
      { key: 'prompt', label: 'Image Description', type: 'textarea', placeholder: 'A futuristic city at sunset...', required: true },
      { key: 'model', label: 'Model', type: 'select', options: [
        { value: 'dall-e-3', label: 'DALL-E 3 (Best)' },
        { value: 'dall-e-2', label: 'DALL-E 2 (Faster)' },
      ]},
      { key: 'size', label: 'Size', type: 'select', options: [
        { value: '1024x1024', label: '1024x1024 (Square)' },
        { value: '1792x1024', label: '1792x1024 (Landscape)' },
        { value: '1024x1792', label: '1024x1792 (Portrait)' },
      ]},
      { key: 'quality', label: 'Quality', type: 'select', options: [
        { value: 'standard', label: 'Standard' },
        { value: 'hd', label: 'HD (More Detail)' },
      ]},
      { key: 'style', label: 'Style', type: 'select', options: [
        { value: 'vivid', label: 'Vivid (Vibrant)' },
        { value: 'natural', label: 'Natural (Realistic)' },
      ]},
    ],
  },
  {
    type: 'action_stability_image',
    category: 'apps',
    name: 'Stable Diffusion',
    icon: '🖼️',
    color: '#9333ea',
    description: 'Generate images with Stable Diffusion API',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Image' }],
    defaultData: { apiKey: '', prompt: '', negativePrompt: '', size: '1024x1024', steps: 30 },
    fields: [
      { key: 'apiKey', label: 'Stability AI Key', type: 'password', placeholder: 'sk-...', required: true },
      { key: 'prompt', label: 'Prompt', type: 'textarea', placeholder: 'A beautiful landscape...', required: true },
      { key: 'negativePrompt', label: 'Negative Prompt', type: 'textarea', placeholder: 'blurry, low quality...' },
      { key: 'size', label: 'Size', type: 'select', options: [
        { value: '512x512', label: '512x512' },
        { value: '1024x1024', label: '1024x1024' },
      ]},
      { key: 'steps', label: 'Steps', type: 'select', options: [
        { value: '20', label: '20 (Fast)' },
        { value: '30', label: '30 (Balanced)' },
        { value: '50', label: '50 (Quality)' },
      ]},
    ],
  },

  // === SYSTEM ACTIONS ===
  {
    type: 'action_screenshot',
    category: 'apps',
    name: 'Screenshot',
    icon: '📸',
    color: '#6366f1',
    description: 'Capture screenshot of screen or window',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Image Path' }],
    defaultData: { savePath: '', display: '0', format: 'png' },
    fields: [
      { key: 'savePath', label: 'Save Path', type: 'file-save', placeholder: '/path/to/screenshot.png', required: true, fileTypes: ['.png', '.jpg'] },
      { key: 'display', label: 'Display', type: 'select', options: [
        { value: '0', label: 'Primary Display' },
        { value: '1', label: 'Display 2' },
        { value: '2', label: 'Display 3' },
        { value: 'all', label: 'All Displays' },
      ]},
      { key: 'format', label: 'Format', type: 'select', options: [
        { value: 'png', label: 'PNG' },
        { value: 'jpg', label: 'JPEG' },
      ]},
    ],
  },
  {
    type: 'action_play_sound',
    category: 'apps',
    name: 'Play Sound',
    icon: '🔊',
    color: '#22c55e',
    description: 'Play a sound notification',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Done' }],
    defaultData: { sound: 'beep', customPath: '' },
    fields: [
      { key: 'sound', label: 'Sound', type: 'select', options: [
        { value: 'beep', label: 'Beep' },
        { value: 'success', label: 'Success' },
        { value: 'error', label: 'Error' },
        { value: 'notification', label: 'Notification' },
        { value: 'custom', label: 'Custom File' },
      ]},
      { key: 'customPath', label: 'Custom Sound File', type: 'file', placeholder: '/path/to/sound.mp3', fileTypes: ['.mp3', '.wav'] },
    ],
  },

  // === TEXT TO SPEECH ===
  {
    type: 'action_tts',
    category: 'apps',
    name: 'Text to Speech',
    icon: '🗣️',
    color: '#8b5cf6',
    description: 'Convert text to speech audio',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Audio' }],
    defaultData: { provider: 'openai', apiKey: '', text: '', voice: 'alloy', savePath: '' },
    fields: [
      { key: 'provider', label: 'Provider', type: 'select', options: [
        { value: 'openai', label: 'OpenAI TTS' },
        { value: 'elevenlabs', label: 'ElevenLabs' },
      ]},
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'sk-... or xi-...', required: true },
      { key: 'text', label: 'Text', type: 'textarea', placeholder: '{{output}} or text to speak', required: true },
      { key: 'voice', label: 'Voice', type: 'select', options: [
        { value: 'alloy', label: 'Alloy (Neutral)' },
        { value: 'echo', label: 'Echo (Male)' },
        { value: 'fable', label: 'Fable (British)' },
        { value: 'onyx', label: 'Onyx (Deep)' },
        { value: 'nova', label: 'Nova (Female)' },
        { value: 'shimmer', label: 'Shimmer (Soft)' },
      ]},
      { key: 'savePath', label: 'Save To (optional)', type: 'file-save', placeholder: '/path/to/audio.mp3', fileTypes: ['.mp3'] },
    ],
  },

  // === FORGEFLOW INTERNAL ===
  {
    type: 'app_settings_get',
    category: 'apps',
    name: 'Get App Setting',
    icon: '⚙️',
    color: '#3b82f6',
    description: 'Get a configuration setting from ForgeFlow',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Value' }],
    defaultData: { key: '' },
    fields: [
      { key: 'key', label: 'Setting Key', type: 'text', placeholder: 'openai_api_key', required: true },
    ],
  },
  {
    type: 'app_settings_set',
    category: 'apps',
    name: 'Set App Setting',
    icon: '⚙️',
    color: '#3b82f6',
    description: 'Update a configuration setting in ForgeFlow',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Done' }],
    defaultData: { key: '', value: '' },
    fields: [
      { key: 'key', label: 'Setting Key', type: 'text', placeholder: 'openai_api_key', required: true },
      { key: 'value', label: 'New Value', type: 'textarea', placeholder: '{{output}} or text', required: true },
    ],
  },
  {
    type: 'app_secret_get',
    category: 'apps',
    name: 'Get Secret',
    icon: '🔒',
    color: '#3b82f6',
    description: 'Retrieve a secret from the secure vault (Requires Auth Key)',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Secret' }],
    defaultData: { key: '' },
    fields: [
      { key: 'key', label: 'Secret Name', type: 'text', placeholder: 'my_api_key', required: true },
    ],
  },
  {
    type: 'app_secret_set',
    category: 'apps',
    name: 'Set Secret',
    icon: '🔒',
    color: '#3b82f6',
    description: 'Store a secret in the secure vault',
    inputs: [{ id: 'in', type: 'input' }],
    outputs: [{ id: 'out', type: 'output', label: 'Done' }],
    defaultData: { key: '', value: '' },
    fields: [
      { key: 'key', label: 'Secret Name', type: 'text', placeholder: 'my_api_key', required: true },
      { key: 'value', label: 'Secret Value', type: 'password', placeholder: '...', required: true },
    ],
  },
];
