#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Read version from central source
const versionFile = path.join(__dirname, '..', 'version.json');
const { version } = JSON.parse(fs.readFileSync(versionFile, 'utf8'));

console.log(`Syncing version ${version} across project files...`);

// Update wails.json
const wailsPath = path.join(__dirname, '..', 'wails.json');
const wailsConfig = JSON.parse(fs.readFileSync(wailsPath, 'utf8'));
wailsConfig.info.productVersion = version;
fs.writeFileSync(wailsPath, JSON.stringify(wailsConfig, null, 2) + '\n');
console.log('✓ Updated wails.json');

// Update frontend/package.json
const packagePath = path.join(__dirname, '..', 'frontend', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
packageJson.version = version;
fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2) + '\n');
console.log('✓ Updated frontend/package.json');

// Update app.go
const appGoPath = path.join(__dirname, '..', 'app.go');
let appGoContent = fs.readFileSync(appGoPath, 'utf8');
appGoContent = appGoContent.replace(/"version":\s*"[^"]+"/g, `"version": "${version}"`);
fs.writeFileSync(appGoPath, appGoContent);
console.log('✓ Updated app.go');

// Update build/splash.html
const splashPath = path.join(__dirname, '..', 'build', 'splash.html');
if (fs.existsSync(splashPath)) {
  let splashContent = fs.readFileSync(splashPath, 'utf8');
  splashContent = splashContent.replace(/<p class="version">v[^<]+<\/p>/g, `<p class="version">v${version}</p>`);
  fs.writeFileSync(splashPath, splashContent);
  console.log('✓ Updated build/splash.html');
}

// Create version constant file for frontend
const versionTsPath = path.join(__dirname, '..', 'frontend', 'src', 'version.ts');
const versionTsContent = `// Auto-generated by scripts/sync-version.js
// DO NOT EDIT MANUALLY - Edit version.json instead

export const APP_VERSION = '${version}';
`;
fs.writeFileSync(versionTsPath, versionTsContent);
console.log('✓ Created frontend/src/version.ts');

console.log(`\nVersion ${version} synced successfully!`);
