// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function Confirm(arg1:string,arg2:string):Promise<boolean>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetDataDir():Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;
