// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetExecution(arg1) {
  return window['go']['main']['Engine']['GetExecution'](arg1);
}

export function GetExecutions() {
  return window['go']['main']['Engine']['GetExecutions']();
}

export function RunFlow(arg1) {
  return window['go']['main']['Engine']['RunFlow'](arg1);
}

export function StopExecution(arg1) {
  return window['go']['main']['Engine']['StopExecution'](arg1);
}
