// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetExecution(arg1:string):Promise<main.FlowExecution>;

export function GetExecutions():Promise<Array<main.FlowExecution>>;

export function RunFlow(arg1:string):Promise<main.FlowExecution>;

export function StopExecution(arg1:string):Promise<void>;
