// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFlow(arg1:string):Promise<void>;

export function Init():Promise<void>;

export function ListFlows():Promise<Array<Record<string, any>>>;

export function LoadFlow(arg1:string):Promise<string>;

export function LoadSettings():Promise<string>;

export function SaveFlow(arg1:string):Promise<string>;

export function SaveSettings(arg1:string):Promise<void>;
