// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFlow(arg1) {
  return window['go']['main']['Storage']['DeleteFlow'](arg1);
}

export function Init() {
  return window['go']['main']['Storage']['Init']();
}

export function ListFlows() {
  return window['go']['main']['Storage']['ListFlows']();
}

export function LoadFlow(arg1) {
  return window['go']['main']['Storage']['LoadFlow'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['Storage']['LoadSettings']();
}

export function SaveFlow(arg1) {
  return window['go']['main']['Storage']['SaveFlow'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['Storage']['SaveSettings'](arg1);
}
